namespace TEMO.AI.Ai;

internal static class ImageStyleCatalog
{
    public static readonly ImageStyle[] RealisticTheme =
    [
        new("Luxury Lifestyle", "Luxury Lifestyle"),
        new("Minimalist Living", "Minimalist Living"),
        new("Modern Professional", "Modern Professional"),
        new("Digital Nomad", "Digital Nomad"),
        new("Weekend Getaway", "Weekend Getaway"),
        new("High Fashion", "High Fashion"),
        new("Street Fashion", "Street Fashion"),
        new("Business Formal", "Business Formal"),
        new("Casual Chic", "Casual Chic"),
        new("Summer Collection", "Summer Collection"),
        new("Winter Collection", "Winter Collection"),
        new("Adventure Explorer", "Adventure Explorer"),
        new("Cultural Experience", "Cultural Experience"),
        new("City Exploration", "City Exploration"),
        new("Quiet Luxury", "Quiet Luxury"),
        new("Old Money", "Old Money"),
        new("Modern Luxury", "Modern Luxury"),
        new("Timeless Elegance", "Timeless Elegance"),
        new("Elite Lifestyle", "Elite Lifestyle"),
        new("Editorial Fashion", "Editorial Fashion"),
        new("Haute Couture", "Haute Couture"),
        new("Luxury Streetwear", "Luxury Streetwear"),
        new("Monochrome Fashion", "Monochrome Fashion"),
        new("Seasonal Collection", "Seasonal Collection"),
        new("Beauty Editorial", "Beauty Editorial"),
        new("Natural Glow", "Natural Glow"),
        new("Glamorous Night", "Glamorous Night"),
        new("Soft Elegance", "Soft Elegance"),
        new("Effortless Chic", "Effortless Chic"),
        new("Executive Leadership", "Executive Leadership"),
        new("Visionary Entrepreneur", "Visionary Entrepreneur"),
        new("Future CEO", "Future CEO"),
        new("Professional Excellence", "Professional Excellence"),
        new("Corporate Confidence", "Corporate Confidence"),
        new("Career Achievement", "Career Achievement"),
        new("Innovation Leader", "Innovation Leader"),
        new("Business Networking", "Business Networking"),
        new("Workplace Collaboration", "Workplace Collaboration"),
        new("Digital Future", "Digital Future"),
        new("Connected World", "Connected World"),
        new("Smart Workspace", "Smart Workspace"),
        new("Next Generation", "Next Generation"),
        new("Around The World", "Around The World"),
        new("Family Bonding", "Family Bonding"),
        new("Best Friends", "Best Friends"),
        new("Celebration Moment", "Celebration Moment"),
        new("Wedding Inspiration", "Wedding Inspiration"),
        new("Romantic Getaway", "Romantic Getaway"),
        new("Parenthood", "Parenthood"),
        new("Togetherness", "Togetherness"),
        new("Community Life", "Community Life"),
    ];

    public static readonly ImageStyle[] StylizedTheme =
    [
        new("Floating Island Kingdom", "Floating Island Kingdom"),
        new("Crystal Cave Sanctuary", "Crystal Cave Sanctuary"),
        new("Cyberpunk Night Market", "Cyberpunk Night Market"),
        new("Cozy Forest Cabin", "Cozy Forest Cabin"),
        new("Dragon Rider Academy", "Dragon Rider Academy"),
        new("Underwater Crystal City", "Underwater Crystal City"),
        new("Steampunk Airship Dock", "Steampunk Airship Dock"),
        new("Samurai Bamboo Forest", "Samurai Bamboo Forest"),
        new("Moonlit Shrine Festival", "Moonlit Shrine Festival"),
        new("Pirate Treasure Island", "Pirate Treasure Island"),
        new("Desert Caravan Journey", "Desert Caravan Journey"),
        new("Ancient Jungle Temple", "Ancient Jungle Temple"),
        new("Neon Arcade District", "Neon Arcade District"),
        new("Space Colony Alpha", "Space Colony Alpha"),
        new("Haunted Victorian Manor", "Haunted Victorian Manor"),
        new("Candy Kingdom Parade", "Candy Kingdom Parade"),
        new("Robot Repair Garage", "Robot Repair Garage"),
        new("Fairy Village Morning", "Fairy Village Morning"),
        new("Ice Palace Ballroom", "Ice Palace Ballroom"),
        new("Volcano Blacksmith Forge", "Volcano Blacksmith Forge"),
        new("Mushroom Village Market", "Mushroom Village Market"),
        new("Sky Whale Migration", "Sky Whale Migration"),
        new("Hidden Ninja Village", "Hidden Ninja Village"),
        new("Floating Garden Palace", "Floating Garden Palace"),
        new("Magic Potion Shop", "Magic Potion Shop"),
        new("Monster Café Downtown", "Monster Café Downtown"),
        new("Secret Wizard Library", "Secret Wizard Library"),
        new("Deep Ocean Ruins", "Deep Ocean Ruins"),
        new("Clockwork City Center", "Clockwork City Center"),
        new("Alien Jungle Expedition", "Alien Jungle Expedition"),
        new("Viking Harbor Festival", "Viking Harbor Festival"),
        new("Gothic Cathedral Hall", "Gothic Cathedral Hall"),
        new("Sakura Riverside Walk", "Sakura Riverside Walk"),
        new("Snow Mountain Monastery", "Snow Mountain Monastery"),
        new("Royal Castle Banquet", "Royal Castle Banquet"),
        new("Ancient Observatory", "Ancient Observatory"),
        new("Lost Desert Kingdom", "Lost Desert Kingdom"),
        new("Sky Train Terminal", "Sky Train Terminal"),
        new("Infinity Railway", "Infinity Railway"),
        new("Dreamworld Carnival", "Dreamworld Carnival"),
        new("Mirror Dimension Gate", "Mirror Dimension Gate"),
        new("Time Traveler Station", "Time Traveler Station"),
        new("Mechanical Jungle", "Mechanical Jungle"),
        new("Crystal Dragon Nest", "Crystal Dragon Nest"),
        new("Floating Waterfall Village", "Floating Waterfall Village"),
        new("Sunset Beach Festival", "Sunset Beach Festival"),
        new("Ghost Lantern Alley", "Ghost Lantern Alley"),
        new("Ancient Tree Kingdom", "Ancient Tree Kingdom"),
        new("Hidden Elf Forest", "Hidden Elf Forest"),
        new("Galaxy Observatory", "Galaxy Observatory"),
        new("Floating Marketplace", "Floating Marketplace"),
        new("Celestial Palace Garden", "Celestial Palace Garden"),
        new("Ancient Stone Coliseum", "Ancient Stone Coliseum"),
        new("Underground Crystal Mine", "Underground Crystal Mine"),
        new("Coral Reef Kingdom", "Coral Reef Kingdom"),
        new("Sky Fortress Citadel", "Sky Fortress Citadel"),
        new("Forgotten Library", "Forgotten Library"),
        new("Moon Base Hangar", "Moon Base Hangar"),
        new("Neon Rain Alley", "Neon Rain Alley"),
        new("Bio-Luminescent Forest", "Bio-Luminescent Forest"),
        new("Giant Tree Village", "Giant Tree Village"),
        new("Sacred Lotus Temple", "Sacred Lotus Temple"),
        new("Mystic Waterfall Shrine", "Mystic Waterfall Shrine"),
        new("Desert Oasis Bazaar", "Desert Oasis Bazaar"),
        new("Frozen Harbor Town", "Frozen Harbor Town"),
        new("Floating Lantern Festival", "Floating Lantern Festival"),
        new("Sky Bridge Kingdom", "Sky Bridge Kingdom"),
        new("Clock Tower Plaza", "Clock Tower Plaza"),
        new("Secret Alchemy Lab", "Secret Alchemy Lab"),
        new("Enchanted Flower Valley", "Enchanted Flower Valley"),
        new("Floating Monastery", "Floating Monastery"),
        new("Underground Lake City", "Underground Lake City"),
        new("Pirate Harbor Tavern", "Pirate Harbor Tavern"),
        new("Dragon Temple Summit", "Dragon Temple Summit"),
        new("Hidden Bamboo Hot Spring", "Hidden Bamboo Hot Spring"),
        new("Mechanical Factory District", "Mechanical Factory District"),
        new("Abandoned Space Station", "Abandoned Space Station"),
        new("Starship Command Deck", "Starship Command Deck"),
        new("Cosmic Garden", "Cosmic Garden"),
        new("Asteroid Mining Colony", "Asteroid Mining Colony"),
        new("Crystal Mountain Pass", "Crystal Mountain Pass"),
        new("Magic Forest Path", "Magic Forest Path"),
        new("Ruined Sky Temple", "Ruined Sky Temple"),
        new("Ancient Lighthouse", "Ancient Lighthouse"),
        new("Fairy Mushroom Grove", "Fairy Mushroom Grove"),
        new("Marble Royal Courtyard", "Marble Royal Courtyard"),
        new("Steam Locomotive Station", "Steam Locomotive Station"),
        new("Floating Tea House", "Floating Tea House"),
        new("Forgotten Battlefield", "Forgotten Battlefield"),
        new("Royal Throne Chamber", "Royal Throne Chamber"),
        new("Clockwork Workshop", "Clockwork Workshop"),
        new("Floating Crystal Bridge", "Floating Crystal Bridge"),
        new("Stormwatch Cliff", "Stormwatch Cliff"),
        new("Cave of Glowing Crystals", "Cave of Glowing Crystals"),
        new("Celestial Observatory", "Celestial Observatory"),
        new("Mystic Stone Circle", "Mystic Stone Circle"),
        new("Sunken Pirate Ship", "Sunken Pirate Ship"),
        new("Autumn Maple Village", "Autumn Maple Village"),
        new("Rainbow Waterfall", "Rainbow Waterfall"),
        new("Eternal Sakura Garden", "Eternal Sakura Garden"),
        new("Upside-Down City", "Upside-Down City"),
        new("Gravity-Free Garden", "Gravity-Free Garden"),
        new("Endless Staircase World", "Endless Staircase World"),
        new("Floating Clock Tower", "Floating Clock Tower"),
        new("Living Book Library", "Living Book Library"),
        new("Origami Village", "Origami Village"),
        new("Ink Painting Realm", "Ink Painting Realm"),
        new("Watercolor Wonderland", "Watercolor Wonderland"),
        new("Sketchbook Universe", "Sketchbook Universe"),
        new("Giant Toy Room", "Giant Toy Room"),
        new("Miniature Kitchen World", "Miniature Kitchen World"),
        new("Dollhouse Mansion", "Dollhouse Mansion"),
        new("Living Chess Kingdom", "Living Chess Kingdom"),
        new("Card Castle Arena", "Card Castle Arena"),
        new("Domino City", "Domino City"),
        new("Marble Maze World", "Marble Maze World"),
        new("Balloon Sky Village", "Balloon Sky Village"),
        new("Bubble Ocean Kingdom", "Bubble Ocean Kingdom"),
        new("Cloud Bakery", "Cloud Bakery"),
        new("Cookie Castle", "Cookie Castle"),
        new("Chocolate Village", "Chocolate Village"),
        new("Candy Factory World", "Candy Factory World"),
        new("Ice Cream Paradise", "Ice Cream Paradise"),
        new("Honey Forest", "Honey Forest"),
        new("Giant Fruit Garden", "Giant Fruit Garden"),
        new("Tea Wonderland", "Tea Wonderland"),
        new("Coffee City", "Coffee City"),
        new("Floating Dessert Island", "Floating Dessert Island"),
        new("Popcorn Carnival", "Popcorn Carnival"),
        new("Music Festival Kingdom", "Music Festival Kingdom"),
        new("Piano Bridge", "Piano Bridge"),
        new("Violin Forest", "Violin Forest"),
        new("Crystal Concert Hall", "Crystal Concert Hall"),
        new("Singing Mountain", "Singing Mountain"),
        new("Dancing Lantern Town", "Dancing Lantern Town"),
        new("Rhythm City", "Rhythm City"),
        new("Echo Canyon", "Echo Canyon"),
        new("Melody Garden", "Melody Garden"),
        new("Symphony Palace", "Symphony Palace"),
        new("Dreamcatcher Valley", "Dreamcatcher Valley"),
        new("Moonflower Garden", "Moonflower Garden"),
        new("Sleeping Giant Forest", "Sleeping Giant Forest"),
        new("Whispering Woods", "Whispering Woods"),
        new("Starfall Meadow", "Starfall Meadow"),
        new("Aurora Sanctuary", "Aurora Sanctuary"),
        new("Eternal Twilight", "Eternal Twilight"),
        new("Golden Sunrise Valley", "Golden Sunrise Valley"),
        new("Celestial Waterfall", "Celestial Waterfall"),
        new("Infinite Horizon", "Infinite Horizon"),
        new("Celestial Throne", "Celestial Throne"),
        new("Skyforge Citadel", "Skyforge Citadel"),
        new("Eternal Flame Temple", "Eternal Flame Temple"),
        new("Forgotten Crown Hall", "Forgotten Crown Hall"),
        new("Astral Gateway", "Astral Gateway"),
        new("Sacred Moon Altar", "Sacred Moon Altar"),
        new("Sunken Crystal Palace", "Sunken Crystal Palace"),
        new("Heavenly Bamboo Garden", "Heavenly Bamboo Garden"),
        new("Stormcaller Peak", "Stormcaller Peak"),
        new("Frozen Crystal Fortress", "Frozen Crystal Fortress"),
        new("Emerald Jungle Kingdom", "Emerald Jungle Kingdom"),
        new("Obsidian Canyon", "Obsidian Canyon"),
        new("Golden Sand Citadel", "Golden Sand Citadel"),
        new("Sapphire Lagoon", "Sapphire Lagoon"),
        new("Mystic River Crossing", "Mystic River Crossing"),
        new("Ancient Spirit Grove", "Ancient Spirit Grove"),
        new("Echoing Cavern", "Echoing Cavern"),
        new("Twilight Watchtower", "Twilight Watchtower"),
        new("Moonstone Sanctuary", "Moonstone Sanctuary"),
        new("Starlight Harbor", "Starlight Harbor"),
        new("Cosmic Cathedral", "Cosmic Cathedral"),
        new("Infinity Observatory", "Infinity Observatory"),
        new("Nebula Garden", "Nebula Garden"),
        new("Solar Temple", "Solar Temple"),
        new("Lunar Fortress", "Lunar Fortress"),
        new("Comet Bridge", "Comet Bridge"),
        new("Planetary Archive", "Planetary Archive"),
        new("Stellar Library", "Stellar Library"),
        new("Astral Harbor", "Astral Harbor"),
        new("Orbit Control Center", "Orbit Control Center"),
        new("Ancient Guardian Arena", "Ancient Guardian Arena"),
        new("Titan’s Workshop", "Titan’s Workshop"),
        new("Phoenix Sanctuary", "Phoenix Sanctuary"),
        new("Griffin Highlands", "Griffin Highlands"),
        new("Leviathan Reef", "Leviathan Reef"),
        new("Spirit Beast Valley", "Spirit Beast Valley"),
        new("Celestial Aviary", "Celestial Aviary"),
        new("Dragonforge Keep", "Dragonforge Keep"),
        new("Rune Stone Circle", "Rune Stone Circle"),
        new("Arcane Vault", "Arcane Vault"),
        new("Hidden King’s Tomb", "Hidden King’s Tomb"),
        new("Eternal Bloom Garden", "Eternal Bloom Garden"),
        new("Whispering Marsh", "Whispering Marsh"),
        new("Shattered Sky Temple", "Shattered Sky Temple"),
        new("Crystal Frontier", "Crystal Frontier"),
        new("Horizon Gateway", "Horizon Gateway"),
        new("Sacred World Tree", "Sacred World Tree"),
        new("Valley of Giants", "Valley of Giants"),
        new("Endless Starfield", "Endless Starfield"),
        new("Realm of Light", "Realm of Light"),
    ];

    public static readonly ImageStyle[] All = [.. RealisticTheme, .. StylizedTheme];

    private const string KeyRealistic = "style-realistic";
    private const string KeyStylized  = "style-stylized";

    public static ImageStyle Random(Random rng)
    {
        var (pool, key) = rng.Next(2) == 0 ? (RealisticTheme, KeyRealistic) : (StylizedTheme, KeyStylized);
        return PromptUsedStore.Pick(key, pool, s => s.Name, rng, 1)[0];
    }

    public static ImageStyle RandomForRender(Random rng, ImageStyle render)
    {
        var (list, key) = ImageRenderCatalog.IsRealistic(render)
            ? (RealisticTheme, KeyRealistic)
            : (StylizedTheme, KeyStylized);
        return PromptUsedStore.Pick(key, list, s => s.Name, rng, 1)[0];
    }
}
