namespace TEMO.AI;

internal static class ProjectComponentSync
{
    private const string GeneratedCssRel = "styles/sections.generated.css";

    public static void Sync(string projectPath, IReadOnlyList<LayoutComponent> components)
    {
        if (EnsureComponents(projectPath, components) is not { } active) return;
        RemoveOrphans(projectPath, active);
    }

    public static IReadOnlyList<SectionDefinition>? EnsureComponents(
        string projectPath, IReadOnlyList<LayoutComponent> components)
    {
        if (string.IsNullOrWhiteSpace(projectPath) || !Directory.Exists(projectPath)) return null;

        ComponentStore.EnsureSeeded();
        SectionCatalog.Reload();

        var active = components
            .Select(EnsureDefinition)
            .Where(x => x is not null)
            .Cast<SectionDefinition>()
            .GroupBy(x => x.ComponentName, StringComparer.Ordinal)
            .Select(g => g.First())
            .ToList();

        if (active.Count == 0) return null;

        foreach (var definition in active)
            ComponentStore.CopyToProjectIfMissing(projectPath, definition);

        return active;
    }

    public static void RemoveOrphans(string projectPath, IReadOnlyList<SectionDefinition> active)
    {
        if (string.IsNullOrWhiteSpace(projectPath) || !Directory.Exists(projectPath) || active.Count == 0) return;

        RemoveUnusedProjectComponents(projectPath, active.Select(x => x.Kind).ToHashSet(StringComparer.Ordinal));
        WriteGeneratedCss(projectPath, active);
    }

    private static SectionDefinition? EnsureDefinition(LayoutComponent component)
    {
        var definition = ComponentStore.Find(component.Name) ?? SectionCatalog.FindByComponentName(component.Name);
        if (definition is null) return null;

        component.Kind = definition.Kind;
        component.Variant = definition.Variant;
        component.DisplayName = definition.DisplayName;
        component.ImportPath = definition.ImportPath;
        component.CssImportPath = definition.CssImportPath;
        component.StoreDirectory = definition.StoreDirectory;
        component.AstroFile = definition.AstroFile;
        component.CssFile = definition.CssFile;
        component.HasExternalLink = definition.HasExternalLink;
        return definition;
    }

    private static void RemoveUnusedProjectComponents(string projectPath, HashSet<string> activeKinds)
    {
        RemoveInactive(ProjectPaths.Src(projectPath, Path.Combine("components", "sections")), "*.astro", activeKinds);
        RemoveInactive(ProjectPaths.Src(projectPath, Path.Combine("styles", "sections")), "*.css", activeKinds);
    }

    private static void RemoveInactive(string dir, string pattern, HashSet<string> activeKinds)
    {
        if (!Directory.Exists(dir)) return;

        foreach (var file in Directory.GetFiles(dir, pattern))
            if (!activeKinds.Contains(Path.GetFileNameWithoutExtension(file)))
                Io.DeleteFileWithRetry(file);
    }

    private static void WriteGeneratedCss(string projectPath, IReadOnlyList<SectionDefinition> active)
    {
        var path = ProjectPaths.Src(projectPath, GeneratedCssRel.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        var lines = active
            .Where(x => !string.IsNullOrWhiteSpace(x.CssFile))
            .Select(x => $"@import \"./sections/{x.Kind}.css\";")
            .Distinct(StringComparer.Ordinal)
            .ToList();

        var content = lines.Count == 0
            ? "/* Generated by TEMO.AI. Active section CSS imports appear here. */\n"
            : "/* Generated by TEMO.AI. Do not edit manually. */\n" + string.Join("\n", lines) + "\n";

        File.WriteAllText(path, content, Encoding.UTF8);
    }
}
